name: Poster Upload Confirmation

on:
  push:

jobs:
  display-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show upload success message
        run: echo "Poster Uploaded Successfully"
